# This is a basic workflow to help you get started with Actions

name: Test Install

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install docFx
        shell: powershell
        run: cinst docfx -y
      - name: Install librdkafka
        run: vcpkg install librdkafka
      - name: Update PATH
        run: echo "::add-path::%PROGRAMFILES%\dotnet\"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run dotnet restore -v Minimal
        run: dotnet restore -v Minimal
      - name: Run dotnet build Confluent.Kafka.sln -c Release
        run: dotnet build Confluent.Kafka.sln -c Release
      - name: Run dotnet pack
        run: | 
          dotnet pack src/Confluent.Kafka/Confluent.Kafka.csproj -c Release;
          dotnet pack src/Confluent.SchemaRegistry/Confluent.SchemaRegistry.csproj -c Release;
          dotnet pack src/Confluent.SchemaRegistry.Serdes.Avro/Confluent.SchemaRegistry.Serdes.Avro.csproj -c Release;
          dotnet pack src/Confluent.SchemaRegistry.Serdes.Protobuf/Confluent.SchemaRegistry.Serdes.Protobuf.csproj -c Release;
          dotnet pack src/Confluent.SchemaRegistry.Serdes.Json/Confluent.SchemaRegistry.Serdes.Json.csproj -c Release;
      - name: Run docfx doc/docfx.json
        run: docfx doc/docfx.json
      - name: Run 7z a docs.zip doc/_site/*
        run: 7z a docs.zip doc/_site/*
      - name: Run tests
        run: |
          dotnet test -c Release --no-build test/Confluent.Kafka.UnitTests/Confluent.Kafka.UnitTests.csproj;
          dotnet test -c Release --no-build test/Confluent.SchemaRegistry.UnitTests/Confluent.SchemaRegistry.UnitTests.csproj;
          dotnet test -c Release --no-build test/Confluent.SchemaRegistry.Serdes.UnitTests/Confluent.SchemaRegistry.Serdes.UnitTests.csproj;
      - name: List artifacts
        run: |
          ls ./src/Confluent.Kafka/bin*/Release/*.nupkg;
          ls ./src/Confluent.SchemaRegistry.Serdes.Avro/bin*/Release/*.nupkg;
          ls ./src/Confluent.SchemaRegistry.Serdes.Protobuf/bin*/Release/*.nupkg;
          ls ./src/Confluent.SchemaRegistry.Serdes.Json/bin*/Release/*.nupkg;
          ls ./src/Confluent.SchemaRegistry/bin*/Release/*.nupkg;
          ls ./doc*.zip;
